name: phone_study
description: å­¦ä¹ flutterç”¨

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: 1.0.0
  rxdart: any
#bloc å­¦ä¹ ç”¨
  flutter_bloc: ^4.0.0
#built_value å­¦ä¹ ç”¨
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2
#json_serializable å­¦ä¹ ç”¨
  json_annotation: ^3.0.0
  lpinyin: ^1.0.9
  event_bus: 1.1.1
  provider: ^4.1.3
  google_fonts: ^1.1.0
  http: 0.12.2
  dio: 3.0.9
  #å¤„ç†é¢œæ–‡å­—ç”¨çš„,åˆ¤æ–­åŒ…å«é¢œæ–‡å­—æ–‡æœ¬çš„é•¿åº¦ç”¨è¿™ä¸ª v.characters.length å…·ä½“å‚è€ƒæ–‡ç« æ­¤åŒ…çš„è¯´æ˜Žå’ŒUnicodeçš„çŸ¥è¯†
  #è‡ªå¸¦çš„string.length å’Œ string.runes.length å®Œå…¨æ²¡ç”¨
  #ðŸ˜€ ðŸ‘¨â€ðŸ‘©â€ðŸ‘§â€ðŸ‘¦ (ç¬‘è„¸ ä¸€å®¶4å£) è¿™ä¸¤ä¸ªé¢œæ–‡å­—å çš„é•¿åº¦ä¸ä¸€æ ·å¯ä»¥æ‹¿åŽ»æµ‹è¯•
  #flutter è‡ªå¸¦äº†
  characters: 1.0.0
#  isolate: 2.0.3
  flutter_cache_manager: 1.4.1

# ä½œä¸ºå­¦ä¹ å‚è€ƒ å¼€å§‹
#  waterfall_flow: 2.0.2
#  auto_route: any
#  flutter_layout_grid: 0.10.2
# ä½œä¸ºå­¦ä¹ å‚è€ƒ ç»“æŸ

dev_dependencies:
  flutter_test:
    sdk: flutter
#built_value json_serializable å­¦ä¹ ç”¨
  build_runner: ^1.0.0
#built_value å­¦ä¹ ç”¨
  built_value_generator: ^7.1.0
  pedantic: ^1.4.0
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0
#json_serializable å­¦ä¹ ç”¨
#  json_serializable: ^3.0.0

# ä½œä¸ºå­¦ä¹ å‚è€ƒ å¼€å§‹
#  waterfall_flow: 2.0.2
#  auto_route_generator: any
# ä½œä¸ºå­¦ä¹ å‚è€ƒ ç»“æŸ
# explore ç”¨ å¼€å§‹
  flutter_swiper: 1.1.6
# explore ç”¨ ç»“æŸ

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/guineaPig.jpeg
    - assets/images/xxx.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
